export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGES = 'REMOVE_ERROR_MESSAGES';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
export const SET_IS_EMAIL_VALID = 'SET_IS_EMAIL_VALID';
export const SET_IS_EMAIL_INPUT_LOADING = 'SET_IS_EMAIL_INPUT_LOADING';
export const SET_IS_USERNAME_INPUT_LOADING = 'SET_IS_USERNAME_INPUT_LOADING';
export const SET_IS_LOGGING_IN = 'SET_IS_LOGGING_IN';
export const SET_IS_SIGNING_UP = 'SET_IS_SIGNING_UP';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_LOADED = 'LOGIN_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
